# Week 3 - Some Technical Points on Normalization

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import preprocessing
%matplotlib inline

Points below:
- Make your own Data Frame from scratch
- Normalization done in clearer manner (I hope!)

In [2]:
df = pd.DataFrame() 
print(df) 
print()
print(type(df))
  
# append columns to an empty DataFrame 
df['Humility'] = [2, 2 , 2] 
df['Power'] = [10, 20, 15] 
df['Coolness'] = [1, 2, 3]

#df.head() <-- or this for display
print()
print(df)

Empty DataFrame
Columns: []
Index: []

<class 'pandas.core.frame.DataFrame'>

   Humility  Power  Coolness
0         2     10         1
1         2     20         2
2         2     15         3


In [3]:
asArray = df.values  # gets values of Data Frame into ndArray (other ways too? Why this way here?)
print("Required 2D for normalization:", asArray.shape)
print()
print(asArray)

Required 2D for normalization: (3, 3)

[[ 2 10  1]
 [ 2 20  2]
 [ 2 15  3]]


In [4]:
pre = preprocessing.StandardScaler() # now an empty StandardScalar object
# Since it is empty right now, note how the next lines would give errors if uncommented
#print(pre.mean_) 
#print(np.sqrt(pre.var_))

# Now we set the data inside pre using our ndArray
# Note: The course puts as "asArray(float)""; perhaps to force to float if not? 
pre.fit(asArray)

# Now that fit to data, we can get the mean and standard deviation of each column
print("MEANs:", pre.mean_)  
print("SDs:", np.sqrt(pre.var_))

MEANs: [ 2. 15.  2.]
SDs: [0.         4.0824829  0.81649658]


In [5]:
# can input any ndArray of correct dimnsions to transform:
# - Does NOT change the inputed array
# - Outputs so each column is normalized according to the stored data
# - Does usual z-score operation
pre.transform(asArray)

array([[ 0.        , -1.22474487, -1.22474487],
       [ 0.        ,  1.22474487,  0.        ],
       [ 0.        ,  0.        ,  1.22474487]])

In [6]:
print(asArray) # Note that the ndarray is NOT changed

[[ 2 10  1]
 [ 2 20  2]
 [ 2 15  3]]


In [7]:
# Example of sending a different array to transform
anotherArray = np.array([[2, 0, 1]])
print(anotherArray)
print(pre.transform(anotherArray))

[[2 0 1]]
[[ 0.         -3.67423461 -1.22474487]]


One line approach in the course.

In [8]:
# Doing it like in the course with one line
# Note that it is the same as the above multi-line approach.
normArray = preprocessing.StandardScaler().fit(asArray).transform(asArray.astype(float))
normArray

array([[ 0.        , -1.22474487, -1.22474487],
       [ 0.        ,  1.22474487,  0.        ],
       [ 0.        ,  0.        ,  1.22474487]])